# Generated by Django 4.2.19 on 2025-02-19 21:13

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.CharField(default='Minnesota Vikings', max_length=100)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('college', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('team', models.CharField(default='Minnesota Vikings', max_length=100)),
                ('games_played', models.PositiveIntegerField(blank=True, null=True)),
                ('games_started', models.PositiveIntegerField(blank=True, null=True)),
                ('rushing_attempts', models.PositiveIntegerField(blank=True, null=True)),
                ('rushing_yards', models.PositiveIntegerField(blank=True, null=True)),
                ('rushing_average', models.FloatField(blank=True, null=True)),
                ('rushing_touchdowns', models.PositiveIntegerField(blank=True, null=True)),
                ('receptions', models.PositiveIntegerField(blank=True, null=True)),
                ('receiving_yards', models.PositiveIntegerField(blank=True, null=True)),
                ('receiving_average', models.FloatField(blank=True, null=True)),
                ('longest_reception', models.PositiveIntegerField(blank=True, null=True)),
                ('receiving_touchdowns', models.PositiveIntegerField(blank=True, null=True)),
                ('fumbles', models.PositiveIntegerField(blank=True, null=True)),
                ('fumbles_lost', models.PositiveIntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='core.player')),
            ],
            options={
                'unique_together': {('player', 'season')},
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tv_series', models.CharField(choices=[('Vikings', 'Vikings'), ('Norsemen', 'Norsemen')], db_index=True, max_length=50)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='core.actor')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='core_charac_search__b059e5_gin')],
            },
        ),
    ]
