# Generated by Django 4.2.19 on 2025-02-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_character_unique_together'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='character',
            name='core_charac_search__b059e5_gin',
        ),
        migrations.RemoveField(
            model_name='character',
            name='search_vector',
        ),
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
