# Generated by Django 4.2.19 on 2025-02-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_player_playing_status_player_squad_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='years_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
