# Generated by Django 4.2.19 on 2025-02-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_player_years_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
